In [1]:
import pandas as pd

try:
#reading csv file
    data_set = pd.read_csv('Downloads/youtube_2025_dataset_202504061614.csv')
    data_set.head()
    
except FileNotFoundError as e :
    print(e)

In [2]:
#checking for null values
missing_values = data_set.isnull().sum()
print('Missing values in each column:')
print(missing_values)

Missing values in each column:
Channel Name                      0
Youtuber Name                     0
Total Videos                      0
Best Video                        0
Avg Video Length (min)            0
Total Subscribers                 0
Members Count                     0
AI Generated Content (%)          0
Neural Interface Compatible       0
Metaverse Integration Level    1282
Quantum Computing Topics          0
Holographic Content Rating        0
Engagement Score                  0
Content Value Index               0
dtype: int64

In [3]:
data_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Channel Name                 5000 non-null   object
 1   Youtuber Name                5000 non-null   object
 2   Total Videos                 5000 non-null   int64
 3   Best Video                   5000 non-null   object
 4   Avg Video Length (min)       5000 non-null   float64
 5   Total Subscribers            5000 non-null   int64
 6   Members Count                5000 non-null   int64
 7   AI Generated Content (%)     5000 non-null   int64
 8   Neural Interface Compatible  5000 non-null   bool
 9   Metaverse Integration Level  3718 non-null   object
 10  Quantum Computing Topics     5000 non-null   int64
 11  Holographic Content Rating   5000 non-null   object
 12  Engagement Score             5000 non-null   float64
 13  Content Value Index          5000 non-null   float64
dtypes: bool(1), float64(3), int64(5), object(5)
memory usage: 512.8+ KB

In [4]:
data_set.describe()

,Total Videos,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Quantum Computing Topics,Engagement Score,Content Value Index
count,5000.00000,5000.000000,5.000000e+03,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000
mean,274.43340,24.004540,5.058482e+06,249082.01980,49.328600,10.061400,79974.100470,21.841560
std,131.71675,0.874555,2.890895e+06,143555.47327,29.444246,6.093953,45704.767088,9.863744
min,50.00000,19.100000,1.755000e+03,143.00000,0.000000,0.000000,27.750000,0.000000
25%,159.00000,23.500000,2.547991e+06,127000.75000,24.000000,5.000000,40283.490000,14.200000
50%,274.00000,24.000000,5.105967e+06,252320.50000,49.000000,10.000000,80724.840000,21.800000
75%,389.00000,24.500000,7.541903e+06,371419.25000,76.000000,15.000000,119236.752500,29.700000
max,500.00000,28.900000,9.999975e+06,499991.00000,100.000000,20.000000,158098.630000,44.000000

In [5]:
#handling missing values
data_set = data_set.fillna('Unknown')

In [6]:
data_set.head()

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Neural Interface Compatible,Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
0,Smith-Ross Labs,Eric Patel,68,VR Challenge: Review 2023,24.8,8264152,303319,9,True,Full,5,3D,130655.44,6.2
1,Sandoval PLC Hub,Cynthia Harrington,128,Nanotech Simulation: Analysis 2024,22.9,8768222,384629,62,False,Unknown,4,3D,138624.73,21.4
2,"Jones, Moore and Ho Network",Amanda Walker,282,Metaverse Interface: Analysis 2024,24.0,6163386,361743,31,True,Advanced,6,1D,97442.53,13.5
3,Mitchell-Hooper Labs,Jessica Nelson MD,302,VR Protocol: Review 2023,24.6,4712268,58483,5,False,Unknown,15,1D,74500.50,12.0
4,Wilson LLC Studios,Matthew Sherman,129,Nanotech Simulation: Review 2024,24.6,9592017,333873,63,True,Unknown,12,3D,151648.85,27.3

In [7]:
#checking for duplicates
duplicates = data_set[data_set.duplicated()]
print(duplicates)

#dropping duplicates
data_set.drop_duplicates()

Empty DataFrame
Columns: [Channel Name, Youtuber Name, Total Videos, Best Video, Avg Video Length (min), Total Subscribers, Members Count, AI Generated Content (%), Neural Interface Compatible, Metaverse Integration Level, Quantum Computing Topics, Holographic Content Rating, Engagement Score, Content Value Index]
Index: []

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Neural Interface Compatible,Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
0,Smith-Ross Labs,Eric Patel,68,VR Challenge: Review 2023,24.8,8264152,303319,9,True,Full,5,3D,130655.44,6.2
1,Sandoval PLC Hub,Cynthia Harrington,128,Nanotech Simulation: Analysis 2024,22.9,8768222,384629,62,False,Unknown,4,3D,138624.73,21.4
2,"Jones, Moore and Ho Network",Amanda Walker,282,Metaverse Interface: Analysis 2024,24.0,6163386,361743,31,True,Advanced,6,1D,97442.53,13.5
3,Mitchell-Hooper Labs,Jessica Nelson MD,302,VR Protocol: Review 2023,24.6,4712268,58483,5,False,Unknown,15,1D,74500.50,12.0
4,Wilson LLC Studios,Matthew Sherman,129,Nanotech Simulation: Review 2024,24.6,9592017,333873,63,True,Unknown,12,3D,151648.85,27.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Flores-Daniel Studios,Jasmine Smith,106,AI Challenge: Experience 2023,22.0,2665835,267828,19,True,Full,1,3D,42146.59,6.4
4996,Spencer and Sons Studios,John Rasmussen,130,VR Challenge: Analysis 2023,26.3,136992,20019,67,True,Full,14,4D,2165.83,29.9
4997,Obrien-Roberts Studios,Lisa Burke,179,AI Challenge: Experience 2023,25.2,2314561,407346,99,True,Advanced,5,1D,36592.98,33.2
4998,King Ltd Hub,Steve Diaz,182,VR Synthesis: Showcase 2023,24.5,6954832,308313,1,True,Basic,9,4D,109955.22,6.6
4999,Henry Ltd Studios,Austin Tate,92,AI Simulation: Showcase 2025,25.2,6785166,23263,52,True,Full,8,3D,107272.81,21.2

In [8]:

data_set.columns = data_set.columns.str.replace(' ', '_')
data_set.columns = data_set.columns.str.replace('(', '')
data_set.columns = data_set.columns.str.replace(')', '')
data_set.columns = data_set.columns.str.replace('%', '')

In [10]:
#connecting to MYSQL
import mysql.connector

conn = mysql.connector.connect(
    host = "localhost",
    user = "root",
    password = "#Tharun123#",
    database = "Youtube_data"
)
cursor = conn.cursor(buffered = True)

In [11]:
#creating MYSQL engine
from sqlalchemy import create_engine

engine = create_engine("mysql+mysqlconnector://root:#Tharun123#@localhost/Youtube_data")
print(data_set.columns)
print(data_set.dtypes)

Index(['Channel_Name', 'Youtuber_Name', 'Total_Videos', 'Best_Video',
       'Avg_Video_Length_min', 'Total_Subscribers', 'Members_Count',
       'AI_Generated_Content_', 'Neural_Interface_Compatible',
       'Metaverse_Integration_Level', 'Quantum_Computing_Topics',
       'Holographic_Content_Rating', 'Engagement_Score',
       'Content_Value_Index'],
      dtype='object')
Channel_Name                    object
Youtuber_Name                   object
Total_Videos                     int64
Best_Video                      object
Avg_Video_Length_min           float64
Total_Subscribers                int64
Members_Count                    int64
AI_Generated_Content_            int64
Neural_Interface_Compatible       bool
Metaverse_Integration_Level     object
Quantum_Computing_Topics         int64
Holographic_Content_Rating      object
Engagement_Score               float64
Content_Value_Index            float64
dtype: object

In [12]:
#storing of values in database
data_set.to_sql('data_set', con=engine, if_exists='replace', index=False)

5000

In [13]:
# Total number of videos
cursor.execute("SELECT COUNT(Total_Videos) AS Total_Videos FROM data_set")
res = cursor.fetchall()
df = pd.DataFrame(res, columns=['Total_Videos'])
print(df)

   Total_Videos
0          5000

In [14]:
# Most engaging channels assuming Engagement_Score
cursor.execute("""
    SELECT Channel_Name, SUM(Engagement_Score) AS Total_Engagement
    FROM data_set
    GROUP BY Channel_Name
    ORDER BY Total_Engagement DESC
    LIMIT 10
""")
res = cursor.fetchall()
df = pd.DataFrame(res, columns=['Channel_Name', 'Total_Engagement'])
print(df)

               Channel_Name  Total_Engagement
0          Moore Group Labs         559103.02
1    Smith and Sons Network         455318.67
2       Smith Group Network         401223.68
3          Marshall PLC Hub         377178.62
4        Wilson LLC Studios         376928.88
5            Smith Inc Labs         367983.85
6         Smith LLC Network         348784.16
7  Johnson and Sons Studios         343749.36
8       Allen Group Studios         343151.48
9         Allen Inc Studios         339405.71

In [15]:
# Get the top 5 channels with the most subscribers
cursor.execute("""
    SELECT Channel_Name, Youtuber_Name, Total_Subscribers
    FROM data_set
    ORDER BY Total_Subscribers DESC
    LIMIT 5
""")
res = cursor.fetchall()
df = pd.DataFrame(res, columns=['Channel_Name', 'Youtuber_Name', 'Total_Subscribers'])
print(df)

                         Channel_Name   Youtuber_Name  Total_Subscribers
0  Williams, Burns and Snyder Network  Charles Powell            9999975
1        Villa, Hughes and Ellis Labs      Dennis Orr            9999559
2                   Stone-Palmer Labs    Teresa Smith            9995049
3      Brown, Lopez and Gonzalez Labs    Joseph Munoz            9992512
4   Zavala, Ortega and Cuevas Studios    George Smith            9991900

In [16]:
#Count how many channels use AI-generated content
cursor.execute("""
    SELECT COUNT(*) AS Channels_Using_AI_Content
    FROM data_set
    WHERE AI_Generated_Content_ = 'Yes'
""")
res = cursor.fetchall()
df = pd.DataFrame(res, columns=['Channels_Using_AI_Content'])
print(df)

   Channels_Using_AI_Content
0                         59

In [17]:
# Getting YouTubers and their channels that support neural interfaces 
cursor.execute("""
    SELECT Channel_Name, Youtuber_Name
    FROM data_set
    WHERE Neural_Interface_Compatible = 'Yes' AND Metaverse_Integration_Level != 'None'
""")
res = cursor.fetchall()
df = pd.DataFrame(res, columns=['Channel_Name', 'Youtuber_Name'])
print(df)

                         Channel_Name       Youtuber_Name
0                    Sandoval PLC Hub  Cynthia Harrington
1                Mitchell-Hooper Labs   Jessica Nelson MD
2                   Myers Ltd Network          Anna Berry
3                   Huber Inc Network      Richard Arnold
4                Austin-Bowen Studios         David Clark
...                               ...                 ...
2466            Beck and Sons Studios        Jessica Holt
2467               Strong LLC Studios      Kevin Arellano
2468            Powell-Strickland Hub     Michelle Knight
2469                  Cole-Sharp Labs        Erin Bradley
2470  Whitaker, Horn and Escobar Labs       Sharon Graham

[2471 rows x 2 columns]

In [18]:
#to know unique vales from a given column
cursor.execute("SELECT DISTINCT Metaverse_Integration_Level FROM data_set")
res = cursor.fetchall()
df = pd.DataFrame(res, columns=['Metaverse_Integration_Level'])
print(df)

  Metaverse_Integration_Level
0                        Full
1                     Unknown
2                    Advanced
3                       Basic

In [19]:
# Retrieving the count of entries grouped by each level of metaverse integration
cursor.execute("""
    SELECT Metaverse_Integration_Level, COUNT(*) AS Count
    FROM data_set
    GROUP BY Metaverse_Integration_Level
""")
res = cursor.fetchall()
df = pd.DataFrame(res, columns=['Metaverse_Integration_Level', 'Count'])
print(df)

  Metaverse_Integration_Level  Count
0                        Full   1248
1                     Unknown   1282
2                    Advanced   1234
3                       Basic   1236

In [21]:
# average Engagement_Score for each Metaverse_Integration_Level
cursor.execute("""
    SELECT Metaverse_Integration_Level, AVG(Engagement_Score) AS Avg_Engagement_Score
    FROM data_set
    GROUP BY Metaverse_Integration_Level
""")
res = cursor.fetchall()
df = pd.DataFrame(res, columns=['Metaverse_Integration_Level', 'Avg_Engagement_Score'])
print(df)

  Metaverse_Integration_Level  Avg_Engagement_Score
0                        Full          81392.720136
1                     Unknown          78390.709111
2                    Advanced          79825.544903
3                       Basic          80332.343147

In [22]:
#channels that have Neural_Interface_Compatible set to True
cursor.execute("""
    SELECT Channel_Name, Youtuber_Name
    FROM data_set
    WHERE Neural_Interface_Compatible = 'True'
""")
res = cursor.fetchall()
df = pd.DataFrame(res, columns=['Channel_Name', 'Youtuber_Name'])
print(df)

                         Channel_Name       Youtuber_Name
0                    Sandoval PLC Hub  Cynthia Harrington
1                Mitchell-Hooper Labs   Jessica Nelson MD
2                   Myers Ltd Network          Anna Berry
3                   Huber Inc Network      Richard Arnold
4                Austin-Bowen Studios         David Clark
...                               ...                 ...
2466            Beck and Sons Studios        Jessica Holt
2467               Strong LLC Studios      Kevin Arellano
2468            Powell-Strickland Hub     Michelle Knight
2469                  Cole-Sharp Labs        Erin Bradley
2470  Whitaker, Horn and Escobar Labs       Sharon Graham

[2471 rows x 2 columns]

In [23]:
#customized query
try : 
    while True:
        print("1. Input Query")
        print("2. Exit")
        inp = int(input())
        2if inp == 1:
            print("column names present in dataset are :",data_set.columns)
            query = input("Enter a SQL query to get the data from table name is data_set: ")
            cursor.execute(query)
            res = cursor.fetchall()
            df = pd.DataFrame(res, columns=[
    'Channel_Name', 'Youtuber_Name', 'Total_Videos', 'Best_Video', 'Avg_Video_Length_min',
    'Total_Subscribers', 'Members_Count', 'AI_Generated_Content_', 'Neural_Interface_Compatible',
    'Metaverse_Integration_Level', 'Quantum_Computing_Topics', 'Holographic_Content_Rating',
    'Engagement_Score', 'Content_Value_Index'
])
            print(df)
        else:
            break;
except Exception as e :
    print(e)

1. Input Query
2. Exit

 2